version: '3.9'

services:
  api:
    build: .
    container_name: property_rent_api
    env_file:
      - .env  # optional, can keep other env vars
    environment:
      SPRING_PROFILES_ACTIVE: neon
      PGHOST: ep-cool-waterfall-ahl3fq1x-pooler.c-3.us-east-1.aws.neon.tech
      PGDATABASE: booking-api
      PGUSER: neondb_owner
      PGPASSWORD: npg_pFxc78GfILWa
      PGSSLMODE: require
      PGCHANNELBINDING: require
    ports:
      - "8080:8080"
