spring:
  application:
    name: smart-service-booking

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-cool-waterfall-ahl3fq1x-pooler.c-3.us-east-1.aws.neon.tech:5432/booking-api?sslmode=require}
    username: ${SPRING_DATASOURCE_USERNAME:neondb_owner}
    password: ${SPRING_DATASOURCE_PASSWORD:npg_pFxc78GfILWa}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
