spring:
  application:
    name: smart-service-booking

  datasource:
    url: jdbc:postgresql://ep-cool-waterfall-ahl3fq1x-pooler.c-3.us-east-1.aws.neon.tech/booking-api?sslmode=require
    username: neondb_owner
    password: npg_pFxc78GfILWa
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

# ===============================
# JWT CONFIG
# ===============================
jwt:
  secret: MySuperSecretJwtKeyMySuperSecretJwtKey123456
  expiration: 3600000   # 1 hour

# ===============================
# SWAGGER CONFIG
# ===============================
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  api-docs:
    path: /v3/api-docs



# ===============================
# PAYPAL CONFIG
# ===============================
paypal:
  client-id: AfH8Vyc9EFoesoFycouhCgotm50MMdFN1lykudeM-2gAv3A5GIwlBy7764tmSVTUy9lljACB4LG9grrs
  client-secret: ECzxoxACZ4SxmurULZ40d3Lql51ReuCPq-KtrcgxdQQ3obu4lkavTFE9M_iUo2M9E5oIr8jTdHOD1cR8
  mode: sandbox